version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      JWT_SECRET: "f8be894170864e55c4c61032a71bc462045ead9be377679b54698c181f0b0ff9"
      GOOGLE_CLOUD_API_KEY: "YOUR_GOOGLE_CLOUD_API_KEY"
      PRODUCTION: "false"
      DEFAULT_ADMIN_USERNAME: "admin"
      DEFAULT_ADMIN_PASSWORD: "admin"
      STORAGE_PATH: "/app/storage"
      PYCONVERTER_PATH: "/app/pkg/pyConverter/main.py"
    volumes:
      - ./storage:/app/storage

volumes:
  storage: 
