#!/bin/sh
echo "Generando archivo .env dinámicamente..."
cat <<EOF > /app/.env
PORT=$PORT
JWT_SECRET=$JWT_SECRET
GOOGLE_CLOUD_API_KEY=$GOOGLE_CLOUD_API_KEY
PRODUCTION=$PRODUCTION
DEFAULT_ADMIN_USERNAME=$DEFAULT_ADMIN_USERNAME
DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD
STORAGE_PATH=$STORAGE_PATH
PYCONVERTER_PATH=$PYCONVERTER_PATH
EOF


# Mostrar la dirección IP
ip a
exec /app/main  